"""
    Stem

    This is the demo project for stem  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: bensong2017@hotmail.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import http_client
from http_client.api.config_api import ConfigApi  # noqa: E501


class TestConfigApi(unittest.TestCase):
    """ConfigApi unit test stubs"""

    def setUp(self):
        self.api = ConfigApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_config(self):
        """Test case for get_config

        GetConfig  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
