"""
    Stem

    This is the demo project for stem  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: bensong2017@hotmail.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import http_client
from http_client.api.health_api import HealthApi  # noqa: E501


class TestHealthApi(unittest.TestCase):
    """HealthApi unit test stubs"""

    def setUp(self):
        self.api = HealthApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_health(self):
        """Test case for get_health

        health  # noqa: E501
        """
        pass

    def test_get_metrics(self):
        """Test case for get_metrics

        metrics  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
