"""
    Stem

    This is the demo project for stem  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: bensong2017@hotmail.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import http_client
from http_client.model.api_response import ApiResponse


class TestApiResponse(unittest.TestCase):
    """ApiResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApiResponse(self):
        """Test ApiResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ApiResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
