"""
    Stem

    This is the demo project for stem  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: bensong2017@hotmail.com
    Generated by: https://openapi-generator.tech
"""


from setuptools import setup, find_packages  # noqa: H301

NAME = "http-client"
VERSION = "0.0.1"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = [
  "urllib3 >= 1.25.3",
  "python-dateutil",
]

setup(
    name=NAME,
    version=VERSION,
    description="Stem",
    author="OpenAPI Generator community",
    author_email="bensong2017@hotmail.com",
    url="",
    keywords=["OpenAPI", "OpenAPI-Generator", "Stem"],
    python_requires=">=3.6",
    install_requires=REQUIRES,
    packages=find_packages(exclude=["test", "tests"]),
    include_package_data=True,
    long_description="""\
    This is the demo project for stem  # noqa: E501
    """
)
