openapi: 3.0.0
info:
  contact:
    email: bensong2017@hotmail.com
  description: This is the demo project for stem
  title: Stem
  version: 0.0.1
servers:
- url: http://localhost:9000/api
tags:
- description: config
  name: config
- description: API for health metrics
  name: health
paths:
  /config/connector/{id}:
    get:
      description: Get connector config.
      operationId: GetConfig
      parameters:
      - description: "Connector Id, e.g. sfexpress.test"
        explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      - description: Connector-self Name
        explode: false
        in: query
        name: connector
        required: true
        schema:
          type: string
        style: form
      - description: "Cache that customer ID and name is matched. If the value is\
          \ `disable`, the cache will not be checked"
        explode: false
        in: query
        name: cache
        required: false
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
          description: User ID and Name has been checked successfully.
        "400":
          description: Invalid input.
        "404":
          description: id check failed.
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
          description: id retrieval failed.
      security:
      - ca_key: []
      summary: GetConfig
      tags:
      - config
  /health:
    get:
      operationId: GetHealth
      responses:
        "200":
          content:
            application/json:
              schema:
                type: object
          description: App service health status
      summary: health
      tags:
      - health
  /metrics:
    get:
      operationId: getMetrics
      responses:
        "200":
          content:
            text/plain:
              schema:
                type: string
          description: App metrics
        "400":
          description: Invalid input
        "401":
          description: "Unauthorized: provided apikey is not valid"
        "500":
          description: Server error
      summary: metrics
      tags:
      - health
components:
  schemas:
    ApiResponse:
      example:
        sub_message: sub_message
        code: 0
        data: "{}"
        message: message
        items:
        - "{}"
        - "{}"
      properties:
        code:
          format: int32
          title: code
          type: integer
        message:
          title: message
          type: string
        sub_message:
          description: error message.
          title: sub_message
          type: string
        data:
          title: data
          type: object
        items:
          items:
            type: object
          title: items
          type: array
      title: ApiResponse
      type: object
  securitySchemes:
    ca_key:
      in: header
      name: Authorization
      type: apiKey
